stages:
  - test
  - build
  - deploy

flake8:
  image: python:3.7
  stage: test

  before_script:
    - python -V
    - pip install flake8==3.5.0
    - flake8 --version

  script:
    - flake8 file_hash

wheel:
  image: python:3.7
  stage: build

  before_script:
    - python -V
    - pip install -U setuptools wheel

  script:
    - python setup.py sdist bdist_wheel

  artifacts:
    paths:
      - dist
    expire_in: 1d

  only:
    - tags

wheel:deploy:
  image: python:3.7
  stage: deploy

  dependencies:
    - wheel

  before_script:
    - python -V
    - pip install twine

  script:
    - twine upload -u $PYPI_USER -p $PYPI_TOKEN dist/*

  only:
    refs:
      - tags
    variables:
      - $PYPI_USER
      - $PYPI_TOKEN
